/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module counter_4bit(clk, rst_n, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__inv_2 _06_ (
    .A(count[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_2 _07_ (
    .A1(count[1]),
    .A2(count[0]),
    .B1(count[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and3_2 _08_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor2_2 _09_ (
    .A(_04_),
    .B(_05_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xor2_2 _10_ (
    .A(count[3]),
    .B(_05_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor2_2 _11_ (
    .A(count[1]),
    .B(count[0]),
    .X(_01_)
  );
  sky130_fd_sc_hd__dfrtp_2 _12_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _13_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _14_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _15_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3]),
    .RESET_B(rst_n)
  );
endmodule
