/* Generated by Yosys 0.59+134 (git sha1 34fa8a4ff, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:1.1-11.10" *)
module counter_4bit(clk, reset, count);
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:1.33-1.36" *)
  input clk;
  wire clk;
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:1.49-1.54" *)
  input reset;
  wire reset;
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:1.73-1.78" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:7.20-7.29|/home/jihan/eda/yosys-installs/dev-20251129/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:7.20-7.29|/home/jihan/eda/yosys-installs/dev-20251129/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _07_;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(count[0]),
    .Y(_06_[0])
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(count[0]),
    .B(count[1]),
    .X(_07_[1])
  );
  sky130_fd_sc_hd__nand3_1 _11_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _12_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _13_ (
    .A(_04_),
    .SLEEP(_05_),
    .X(_07_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _14_ (
    .A(count[3]),
    .B(_04_),
    .Y(_07_[3])
  );
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(reset),
    .Y(_03_)
  );
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:3.3-9.6" *)
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(_06_[0]),
    .Q(count[0]),
    .RESET_B(_00_)
  );
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:3.3-9.6" *)
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(clk),
    .D(_07_[1]),
    .Q(count[1]),
    .RESET_B(_01_)
  );
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:3.3-9.6" *)
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(clk),
    .D(_07_[2]),
    .Q(count[2]),
    .RESET_B(_02_)
  );
  (* src = "/home/jihan/projects/units/top/rtl/counter_4bit.sv:3.3-9.6" *)
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(clk),
    .D(_07_[3]),
    .Q(count[3]),
    .RESET_B(_03_)
  );
  assign _06_[31:1] = { 28'h0000000, count[3:1] };
  assign { _07_[31:5], _07_[0] } = { 27'h0000000, _06_[0] };
endmodule
