/* Generated by Yosys 0.60+1 (git sha1 685515865, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:21.1-65.10" *)
module param_counter(clk, rst_n, en, load, load_value, count);
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:26.34-26.37" *)
  input clk;
  wire clk;
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:27.34-27.39" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:28.34-28.36" *)
  input en;
  wire en;
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:29.34-29.38" *)
  input load;
  wire load;
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:30.34-30.44" *)
  input [3:0] load_value;
  wire [3:0] load_value;
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:31.34-31.39" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  sky130_fd_sc_hd__nand2_1 _14_ (
    .A(count[0]),
    .B(en),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(count[1]),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _16_ (
    .A0(_05_),
    .A1(load_value[1]),
    .S(load),
    .X(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _17_ (
    .A1(count[0]),
    .A2(en),
    .B1(load),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a41oi_1 _18_ (
    .A1(count[1]),
    .A2(count[2]),
    .A3(count[0]),
    .A4(en),
    .B1(load),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a31o_1 _19_ (
    .A1(count[1]),
    .A2(count[0]),
    .A3(en),
    .B1(count[2]),
    .X(_08_)
  );
  sky130_fd_sc_hd__a22o_1 _20_ (
    .A1(load),
    .A2(load_value[2]),
    .B1(_07_),
    .B2(_08_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(count[3]),
    .B(_07_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(count[3]),
    .B(load),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(load),
    .A2(load_value[3]),
    .B1(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o21ai_0 _24_ (
    .A1(_07_),
    .A2(_11_),
    .B1(_09_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(load),
    .B(load_value[0]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o21ai_0 _26_ (
    .A1(count[0]),
    .A2(en),
    .B1(_06_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(_12_),
    .B(_13_),
    .Y(_03_)
  );
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:37.5-63.8" *)
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:37.5-63.8" *)
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:37.5-63.8" *)
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/jihan/projects/openlane_flow/designs/param_counter/src/param_counter.sv:37.5-63.8" *)
  sky130_fd_sc_hd__dfrtp_1 _31_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
endmodule
