/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "fsm.sv:2.1-57.10" *)
module fsm_example(clk, rst_n, start, done, busy);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "fsm.sv:7.18-7.22" *)
  output busy;
  wire busy;
  (* src = "fsm.sv:3.18-3.21" *)
  input clk;
  wire clk;
  (* src = "fsm.sv:6.18-6.22" *)
  input done;
  wire done;
  (* src = "fsm.sv:4.18-4.23" *)
  input rst_n;
  wire rst_n;
  (* src = "fsm.sv:5.18-5.23" *)
  input start;
  wire start;
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\RUN" *)
  (* enum_value_10 = "\\HOLD" *)
  (* src = "fsm.sv:17.13-17.18" *)
  (* wiretype = "\\state_t" *)
  wire [1:0] state;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(done),
    .Y(_03_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _05_ (
    .A(state[0]),
    .SLEEP(state[1]),
    .X(busy)
  );
  sky130_fd_sc_hd__nor2_1 _06_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a22o_1 _07_ (
    .A1(_03_),
    .A2(busy),
    .B1(_02_),
    .B2(start),
    .X(_00_)
  );
  sky130_fd_sc_hd__and2_0 _08_ (
    .A(done),
    .B(busy),
    .X(_01_)
  );
  (* src = "fsm.sv:20.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _09_ (
    .CLK(clk),
    .D(_00_),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  (* src = "fsm.sv:20.5-25.8" *)
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_01_),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
endmodule
