// Auto-generated by OpenLane
module param_counter(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input en,
  input load,
  input[3:0] load_value,
  output[3:0] count
);
endmodule
